[tool.poetry]
name = "fastapi-boilerplate"
version = "0.1.0"
description = "FastAPI service for read operations"
authors = ["Tofayel Hyder Abhi <abhihyder7@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">=0.115.12,<0.116.0"
uvicorn = {extras = ["standard"], version = ">=0.34.2,<0.35.0"}
python-dotenv = ">=1.1.0,<2.0.0"
requests = ">=2.32.3,<3.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dev = "run:dev"
start = "run:start"

